logging:
- email-server: 192.168.0.102
  email-to: dmichelson@ashevillenc.gov
  email-from: dmichelson@ashevillenc.gov
  email-subject: Error with versioning!
sde_connections:
- out_folder_path: config/ 
  out_name: editdb.sde 
  database_platform: POSTGRESQL 
  instance: 192.168.0.126
  account_authentication: DATABASE_AUTH 
  username: sde
  password: ytrewq
  save_user_pass: SAVE_USERNAME 
  database: coagisedit
  schema: #
  version_type: #
  version: #
  date: #
  versions:
    - version-name: test1
      parent-version: sde.DEFAULT
      access-permission: PUBLIC
    - version-name: test2
      parent-version: sde.DEFAULT
      access-permission: PUBLIC
    - version-name: test3
      parent-version: sde.DEFAULT
      access-permission: PUBLIC
- out_folder_path: config/
  out_name: warehousedb.sde
  database_platform: POSTGRESQL
  instance: 192.168.0.124
  account_authentication: DATABASE_AUTH
  username: sde
  password: ytrewq
  save_user_pass: SAVE_USERNAME
  database: coagiswarehouse
  schema: #
  version_type: #
  version: #
  date: #
